# Generated by Django 2.2.3 on 2019-08-11 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import utils.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.IntegerField(choices=[(1, '经济管理学院'), (2, '外国语学院'), (3, '会计学院'), (4, '信息工程学院'), (5, '人文学院'), (6, '设计学院'), (7, '传媒学院')], primary_key=True, serialize=False, verbose_name='学院ID')),
                ('name', models.CharField(max_length=20, verbose_name='学院名称')),
            ],
            options={
                'verbose_name': '学院信息',
                'verbose_name_plural': '学院信息',
                'db_table': 'College',
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.IntegerField(choices=[(1, '秘书部'), (2, '组织部'), (3, '外事部'), (4, '宣传部'), (5, '培训部'), (6, '策划部'), (7, '社长团')], primary_key=True, serialize=False, verbose_name='部门ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('url', models.TextField(verbose_name='推文网址')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
                'db_table': 'Dept',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='专业ID')),
                ('name', models.CharField(max_length=20, verbose_name='专业名称')),
                ('college', models.ForeignKey(db_column='college_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.College', verbose_name='学院')),
            ],
            options={
                'verbose_name': '专业信息',
                'verbose_name_plural': '专业信息',
                'db_table': 'Major',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=50, unique=True, verbose_name='微信标识符')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('address', models.CharField(max_length=50, verbose_name='籍贯')),
                ('birthday', models.DateField(blank=True, default=datetime.date.today, verbose_name='生日')),
                ('sex', models.BooleanField(choices=[(True, '男'), (False, '女')], verbose_name='性别')),
                ('grade', models.CharField(max_length=2, verbose_name='年级')),
                ('class_num', models.CharField(max_length=2, verbose_name='班级')),
                ('dorm', models.CharField(max_length=2, verbose_name='宿舍')),
                ('dorm_num', models.CharField(max_length=3, verbose_name='宿舍号')),
                ('introduce', models.TextField(verbose_name='个人介绍')),
                ('join_time', models.DateField(blank=True, default=datetime.date.today, verbose_name='加入时间')),
                ('judge_invalid', models.BooleanField(choices=[(True, '有效'), (False, '无效')], default=False, verbose_name='账号状态')),
                ('college', models.ForeignKey(db_column='college_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.College', verbose_name='学院')),
                ('major', models.ForeignKey(db_column='major_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.Major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late', models.IntegerField(default=0, verbose_name='迟到次数')),
                ('request', models.IntegerField(default=0, verbose_name='请假次数')),
                ('absent', models.IntegerField(default=0, verbose_name='缺席次数')),
                ('finish', models.IntegerField(default=0, verbose_name='完成任务次数')),
                ('overtime', models.IntegerField(default=0, verbose_name='超时完成次数')),
                ('incomplete', models.IntegerField(default=0, verbose_name='未完成次数')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authorization.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '工作记录',
                'verbose_name_plural': '工作记录',
                'db_table': 'UserRecord',
            },
        ),
        migrations.CreateModel(
            name='UserPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_activity', models.BooleanField(choices=[(True, '有'), (False, '无')], default=False, verbose_name='发布活动权限')),
                ('edit_activity', models.BooleanField(choices=[(True, '有'), (False, '无')], default=False, verbose_name='修改活动权限')),
                ('record', models.BooleanField(choices=[(True, '有'), (False, '无')], default=False, verbose_name='签到权限')),
                ('edit_course', models.BooleanField(choices=[(True, '有'), (False, '无')], default=False, verbose_name='修改空课表权限')),
                ('add_article', models.BooleanField(choices=[(True, '有'), (False, '无')], default=False, verbose_name='发布文章权限')),
                ('edit_article', models.BooleanField(choices=[(True, '有'), (False, '无')], default=False, verbose_name='修改文章权限')),
                ('add_image', models.BooleanField(choices=[(True, '有'), (False, '无')], default=False, verbose_name='上传图片权限')),
                ('add_file', models.BooleanField(choices=[(True, '有'), (False, '无')], default=False, verbose_name='上传文档权限')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authorization.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '权限管理',
                'verbose_name_plural': '权限管理',
                'db_table': 'UserPower',
            },
        ),
        migrations.CreateModel(
            name='UserClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, '干事'), (1, '部长'), (2, '社长')], default=0, verbose_name='职位')),
                ('judge_remain', models.BooleanField(choices=[(True, '留任'), (False, '非留任')], default=False, verbose_name='留任')),
                ('dept', models.ForeignKey(db_column='dept_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.Dept', verbose_name='部门')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authorization.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
                'db_table': 'UserClub',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(blank=True, default=datetime.date.today, verbose_name='报名时间')),
                ('dept1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept1', to='authorization.Dept', verbose_name='部门1')),
                ('dept2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept2', to='authorization.Dept', verbose_name='部门2')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authorization.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '注册管理',
                'verbose_name_plural': '注册管理',
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='课表ID')),
                ('mon1', models.CharField(max_length=50, verbose_name='周一1大节')),
                ('mon2', models.CharField(max_length=50, verbose_name='周一2大节')),
                ('mon3', models.CharField(max_length=50, verbose_name='周一3大节')),
                ('mon4', models.CharField(max_length=50, verbose_name='周一4大节')),
                ('mon5', models.CharField(max_length=50, verbose_name='周一5大节')),
                ('tue1', models.CharField(max_length=50, verbose_name='周二1大节')),
                ('tue2', models.CharField(max_length=50, verbose_name='周二2大节')),
                ('tue3', models.CharField(max_length=50, verbose_name='周二3大节')),
                ('tue4', models.CharField(max_length=50, verbose_name='周二4大节')),
                ('tue5', models.CharField(max_length=50, verbose_name='周二5大节')),
                ('wed1', models.CharField(max_length=50, verbose_name='周三1大节')),
                ('wed2', models.CharField(max_length=50, verbose_name='周三2大节')),
                ('wed3', models.CharField(max_length=50, verbose_name='周三3大节')),
                ('wed4', models.CharField(max_length=50, verbose_name='周三4大节')),
                ('wed5', models.CharField(max_length=50, verbose_name='周三5大节')),
                ('thu1', models.CharField(max_length=50, verbose_name='周四1大节')),
                ('thu2', models.CharField(max_length=50, verbose_name='周四2大节')),
                ('thu3', models.CharField(max_length=50, verbose_name='周四3大节')),
                ('thu4', models.CharField(max_length=50, verbose_name='周四4大节')),
                ('thu5', models.CharField(max_length=50, verbose_name='周四5大节')),
                ('fri1', models.CharField(max_length=50, verbose_name='周五1大节')),
                ('fri2', models.CharField(max_length=50, verbose_name='周五2大节')),
                ('fri3', models.CharField(max_length=50, verbose_name='周五3大节')),
                ('fri4', models.CharField(max_length=50, verbose_name='周五4大节')),
                ('fri5', models.CharField(max_length=50, verbose_name='周五5大节')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authorization.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
                'db_table': 'Course',
            },
        ),
    ]
