# Generated by Django 2.2.3 on 2019-08-11 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20190811_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fri1',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周五1大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fri2',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周五2大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fri3',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周五3大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fri4',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周五4大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fri5',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周五5大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mon1',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周一1大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mon2',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周一2大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mon3',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周一3大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mon4',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周一4大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mon5',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周一5大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thu1',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周四1大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thu2',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周四2大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thu3',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周四3大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thu4',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周四4大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thu5',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周四5大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tue1',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周二1大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tue2',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周二2大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tue3',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周二3大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tue4',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周二4大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tue5',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周二5大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='wed1',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周三1大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='wed2',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周三2大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='wed3',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周三3大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='wed4',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周三4大节'),
        ),
        migrations.AlterField(
            model_name='course',
            name='wed5',
            field=models.CharField(default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', max_length=35, verbose_name='周三5大节'),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_time',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='报名时间'),
        ),
    ]
