# Generated by Django 2.2.4 on 2019-08-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190811_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='class_num',
            field=models.CharField(max_length=2, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dorm',
            field=models.CharField(max_length=2, null=True, verbose_name='宿舍'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dorm_num',
            field=models.CharField(max_length=3, null=True, verbose_name='宿舍号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='grade',
            field=models.CharField(max_length=2, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='introduce',
            field=models.TextField(null=True, verbose_name='个人介绍'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.BooleanField(choices=[(True, '男'), (False, '女')], null=True, verbose_name='性别'),
        ),
    ]
