# Generated by Django 2.2.4 on 2019-08-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20190813_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='学院ID'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='dept_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='部门ID'),
        ),
    ]
