# Generated by Django 2.2.4 on 2019-08-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20190815_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': '报名管理', 'verbose_name_plural': '报名管理'},
        ),
    ]
