# Generated by Django 2.2.4 on 2019-08-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20190823_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='url',
        ),
    ]
