# Generated by Django 2.2.4 on 2019-08-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_remove_dept_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='daily',
            field=models.TextField(null=True, verbose_name='日常'),
        ),
        migrations.AddField(
            model_name='dept',
            name='introduce',
            field=models.TextField(null=True, verbose_name='部门介绍'),
        ),
        migrations.AddField(
            model_name='dept',
            name='technology',
            field=models.TextField(null=True, verbose_name='职能'),
        ),
        migrations.AddField(
            model_name='dept',
            name='work',
            field=models.TextField(null=True, verbose_name='工作'),
        ),
    ]
