# Generated by Django 2.2.3 on 2019-08-12 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week', models.IntegerField(choices=[(1, '1周'), (2, '2周'), (3, '3周'), (4, '4周'), (5, '5周'), (6, '6周'), (7, '7周'), (8, '8周'), (9, '9周'), (10, '10周'), (11, '11周'), (12, '12周'), (13, '13周'), (14, '14周'), (15, '15周'), (16, '16周'), (17, '17周')], verbose_name='当前周次')),
                ('register', models.BooleanField(choices=[(True, '开启'), (False, '关闭')], default=False, verbose_name='报名管理')),
                ('course', models.BooleanField(choices=[(True, '开启'), (False, '关闭')], default=False, verbose_name='空课表编辑')),
            ],
            options={
                'verbose_name': '特权',
                'verbose_name_plural': '特权',
                'db_table': 'Master',
            },
        ),
        migrations.CreateModel(
            name='Propagate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name1', models.CharField(max_length=50, verbose_name='图片1名称')),
                ('image1', models.ImageField(blank=True, default='default.png', upload_to='images', verbose_name='图片1')),
                ('image_name2', models.CharField(max_length=50, verbose_name='图片2名称')),
                ('image2', models.ImageField(blank=True, default='default.png', upload_to='images', verbose_name='图片2')),
                ('image_name3', models.CharField(max_length=50, verbose_name='图片3名称')),
                ('image3', models.ImageField(blank=True, default='default.png', upload_to='images', verbose_name='图片3')),
                ('image_name4', models.CharField(max_length=50, verbose_name='图片4名称')),
                ('image4', models.ImageField(blank=True, default='default.png', upload_to='images', verbose_name='图片4')),
                ('image_name5', models.CharField(max_length=50, verbose_name='图片5名称')),
                ('image5', models.ImageField(blank=True, default='default.png', upload_to='images', verbose_name='图片5')),
                ('nature', models.TextField(verbose_name='社团性质')),
                ('activity', models.TextField(verbose_name='社团活动')),
            ],
            options={
                'verbose_name': '社团宣传',
                'verbose_name_plural': '社团宣传',
                'db_table': 'Propagate',
            },
        ),
        migrations.CreateModel(
            name='TimeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField(choices=[(1, '1节'), (2, '2节'), (3, '3节'), (4, '4节'), (5, '5节'), (6, '6节'), (7, '7节'), (8, '8节'), (9, '9节'), (10, '10节'), (11, '晚修结束')], verbose_name='节课')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='上课时间')),
            ],
            options={
                'verbose_name': '课程时间映射',
                'verbose_name_plural': '课程时间映射',
                'db_table': 'TimeMapping',
            },
        ),
    ]
