# Generated by Django 2.2.4 on 2019-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propagate',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='propagate',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='propagate',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='propagate',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片4'),
        ),
        migrations.AlterField(
            model_name='propagate',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片5'),
        ),
    ]
