# Generated by Django 2.2.4 on 2019-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assists', '0002_auto_20190813_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propagate',
            name='image_name1',
            field=models.CharField(max_length=50, null=True, verbose_name='图片1名称'),
        ),
        migrations.AlterField(
            model_name='propagate',
            name='image_name2',
            field=models.CharField(max_length=50, null=True, verbose_name='图片2名称'),
        ),
        migrations.AlterField(
            model_name='propagate',
            name='image_name3',
            field=models.CharField(max_length=50, null=True, verbose_name='图片3名称'),
        ),
        migrations.AlterField(
            model_name='propagate',
            name='image_name4',
            field=models.CharField(max_length=50, null=True, verbose_name='图片4名称'),
        ),
        migrations.AlterField(
            model_name='propagate',
            name='image_name5',
            field=models.CharField(max_length=50, null=True, verbose_name='图片5名称'),
        ),
    ]
