# Generated by Django 2.2.4 on 2019-08-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assists', '0006_auto_20190823_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propagate',
            name='image_name1',
        ),
        migrations.RemoveField(
            model_name='propagate',
            name='image_name2',
        ),
        migrations.RemoveField(
            model_name='propagate',
            name='image_name3',
        ),
        migrations.RemoveField(
            model_name='propagate',
            name='image_name4',
        ),
        migrations.RemoveField(
            model_name='propagate',
            name='image_name5',
        ),
    ]
