# Generated by Django 2.2.4 on 2019-08-18 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0006_auto_20190815_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='活动ID')),
                ('name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('begin_w', models.IntegerField(choices=[(1, '1周'), (2, '2周'), (3, '3周'), (4, '4周'), (5, '5周'), (6, '6周'), (7, '7周'), (8, '8周'), (9, '9周'), (10, '10周'), (11, '11周'), (12, '12周'), (13, '13周'), (14, '14周'), (15, '15周'), (16, '16周'), (17, '17周')], verbose_name='开始周次')),
                ('begin_d', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], verbose_name='开始星期')),
                ('begin_c', models.IntegerField(choices=[(1, '1节'), (2, '2节'), (3, '3节'), (4, '4节'), (5, '5节'), (6, '6节'), (7, '7节'), (8, '8节'), (9, '9节'), (10, '10节')], verbose_name='开始节课')),
                ('end_w', models.IntegerField(choices=[(1, '1周'), (2, '2周'), (3, '3周'), (4, '4周'), (5, '5周'), (6, '6周'), (7, '7周'), (8, '8周'), (9, '9周'), (10, '10周'), (11, '11周'), (12, '12周'), (13, '13周'), (14, '14周'), (15, '15周'), (16, '16周'), (17, '17周')], verbose_name='结束周次')),
                ('end_d', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], verbose_name='结束星期')),
                ('end_c', models.IntegerField(choices=[(1, '1节'), (2, '2节'), (3, '3节'), (4, '4节'), (5, '5节'), (6, '6节'), (7, '7节'), (8, '8节'), (9, '9节'), (10, '10节')], verbose_name='结束节课')),
                ('address', models.CharField(max_length=50, verbose_name='活动地点')),
                ('clothes', models.BooleanField(choices=[(True, '需要'), (False, '不需要')], default=False, verbose_name='社服要求')),
                ('message', models.TextField(verbose_name='活动流程')),
                ('time', models.DateField(blank=True, default=datetime.date.today, verbose_name='发布时间')),
                ('status', models.IntegerField(choices=[(2, '进行中'), (1, '未开始'), (0, '已结束')], default=1, verbose_name='状态')),
                ('judge_delete', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='删除判断')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor', to='authorization.UserInfo', verbose_name='修改者')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='authorization.UserInfo', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='社团物资ID')),
                ('name', models.CharField(max_length=20, verbose_name='物品名称')),
                ('count', models.IntegerField(default=1, verbose_name='物品数量')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_editor', to='authorization.UserInfo', verbose_name='修改者')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_user', to='authorization.UserInfo', verbose_name='添加者')),
            ],
            options={
                'verbose_name': '社团物资',
                'verbose_name_plural': '社团物资',
                'db_table': 'Resource',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='签到ID')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('status', models.IntegerField(choices=[(0, '缺席'), (1, '请假'), (2, '迟到'), (3, '签到'), (4, '忽略'), (5, '未签到')], default=5, verbose_name='状态')),
                ('activity', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, to='apis.Activity', verbose_name='活动')),
                ('recorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_recorder', to='authorization.UserInfo', verbose_name='签到员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_user', to='authorization.UserInfo', verbose_name='工作人员')),
            ],
            options={
                'verbose_name': '签到',
                'verbose_name_plural': '签到',
                'db_table': 'Record',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='活动物资ID')),
                ('name', models.CharField(max_length=20, verbose_name='物品名称')),
                ('count', models.IntegerField(default=1, verbose_name='物品数量')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.BooleanField(choices=[(True, '已完成'), (False, '未完成')], default=False, verbose_name='状态')),
                ('activity', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, to='apis.Activity', verbose_name='活动')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_editor', to='authorization.UserInfo', verbose_name='修改者')),
            ],
            options={
                'verbose_name': '活动物资',
                'verbose_name_plural': '活动物资',
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='图片ID')),
                ('name', models.CharField(max_length=50, verbose_name='图片名称')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='images', verbose_name='图片')),
                ('time', models.DateField(blank=True, default=datetime.date.today, verbose_name='上传时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_user', to='authorization.UserInfo', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='文件ID')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
                ('file', models.FileField(blank=True, default='default.doc', upload_to='documents', verbose_name='文档')),
                ('time', models.DateField(blank=True, default=datetime.date.today, verbose_name='上传时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_user', to='authorization.UserInfo', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'File',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='评论ID')),
                ('message', models.TextField(null=True, verbose_name='内容')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='评论时间')),
                ('activity', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, to='apis.Activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='authorization.UserInfo', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '反思墙',
                'verbose_name_plural': '反思墙',
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('time', models.DateField(blank=True, default=datetime.date.today, verbose_name='发布时间')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_editor', to='authorization.UserInfo', verbose_name='修改者')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_user', to='authorization.UserInfo', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Arrange',
            fields=[
                ('arrange_id', models.CharField(default=utils.id.generate_id, max_length=22, primary_key=True, serialize=False, verbose_name='人员安排ID')),
                ('begin_w', models.IntegerField(choices=[(1, '1周'), (2, '2周'), (3, '3周'), (4, '4周'), (5, '5周'), (6, '6周'), (7, '7周'), (8, '8周'), (9, '9周'), (10, '10周'), (11, '11周'), (12, '12周'), (13, '13周'), (14, '14周'), (15, '15周'), (16, '16周'), (17, '17周')], verbose_name='开始周次')),
                ('begin_d', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], verbose_name='开始星期')),
                ('begin_c', models.IntegerField(choices=[(1, '1节'), (2, '2节'), (3, '3节'), (4, '4节'), (5, '5节'), (6, '6节'), (7, '7节'), (8, '8节'), (9, '9节'), (10, '10节')], verbose_name='开始节课')),
                ('end_w', models.IntegerField(choices=[(1, '1周'), (2, '2周'), (3, '3周'), (4, '4周'), (5, '5周'), (6, '6周'), (7, '7周'), (8, '8周'), (9, '9周'), (10, '10周'), (11, '11周'), (12, '12周'), (13, '13周'), (14, '14周'), (15, '15周'), (16, '16周'), (17, '17周')], verbose_name='结束周次')),
                ('end_d', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], verbose_name='结束星期')),
                ('end_c', models.IntegerField(choices=[(1, '1节'), (2, '2节'), (3, '3节'), (4, '4节'), (5, '5节'), (6, '6节'), (7, '7节'), (8, '8节'), (9, '9节'), (10, '10节')], verbose_name='结束节课')),
                ('message', models.TextField(verbose_name='任务说明')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.BooleanField(choices=[(True, '已完成'), (False, '未完成')], default=False, verbose_name='状态')),
                ('activity', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, to='apis.Activity', verbose_name='活动')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrange_editor', to='authorization.UserInfo', verbose_name='修改者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrange_user', to='authorization.UserInfo', verbose_name='工作人员')),
            ],
            options={
                'verbose_name': '工作安排',
                'verbose_name_plural': '工作安排',
                'db_table': 'Arrange',
            },
        ),
    ]
