# Generated by Django 2.2.4 on 2019-08-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20190818_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
