# Generated by Django 2.2.4 on 2019-08-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20190819_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
    ]
