# Generated by Django 2.2.4 on 2019-08-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20190823_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '社团活动', 'verbose_name_plural': '社团活动'},
        ),
    ]
